using UnityEngine;
using UnityEditor;
using AKSaigyouji.EditorScripting;

namespace AKSaigyouji.Modules.MapGeneration
{
    public static class NodeEditorSettings
    {
        public const int MAJOR_GRID_SPACING = GRID_UNITS_TO_WORLD_UNITS * 50;
        public const int MINOR_GRID_SPACING = GRID_UNITS_TO_WORLD_UNITS * 10;

        /// <summary>
        /// How much space on the UI should represent one unit in the game world.
        /// </summary>
        public const int GRID_UNITS_TO_WORLD_UNITS = 3;

        public const int DEFAULT_NODE_SIZE = 40;
        public const int RESIZE_HANDLE_SIZE = 25;

        public static GUIStyle SelectedNodeStyle { get { return selectedNodeStyle; } }
        public static GUIStyle DefaultNodeStyle { get { return defaultNodeStyle; } }

        static readonly GUIStyle selectedNodeStyle;
        static readonly GUIStyle defaultNodeStyle;

        static readonly RectOffset STYLE_BORDER = new RectOffset(BORDER_SIZE, BORDER_SIZE, BORDER_SIZE, BORDER_SIZE);
        const int BORDER_SIZE = 12;

        const string DEFAULT_BACKGROUND_PATH = "builtin skins/darkskin/images/node1.png";
        const string SELECTED_BACKGROUND_PATH = "builtin skins/darkskin/images/node1 on.png";

        const string ROOT_FOLDER = "AKSaigyouji";
        const string MODULE_FOLDER = "Compound Modules";
        const string MAP_FOLDER = "Maps";
        const string CHART_FOLDER = "Charts";

        /// <summary>
        /// The path to the folder where all assets generated by this project are stored.
        /// </summary>
        public static string PathToRootFolder
        {
            get
            {
                const string parentFolder = "Assets";
                string folderName = ROOT_FOLDER;
                IOHelpers.RequireFolder(parentFolder, folderName);
                return IOHelpers.CombinePath(parentFolder, folderName);
            }
        }

        /// <summary>
        /// Folder containing modules produced by the map editor window. Subfolder of the root folder.
        /// </summary>
        public static string PathToModuleFolder { get { return RequireSubfolder(MODULE_FOLDER); } }

        /// <summary>
        /// Folder containing maps produced by the map editor window. Subfolder of the root folder.
        /// </summary>
        public static string PathToMapFolder { get { return RequireSubfolder(MAP_FOLDER); } }

        /// <summary>
        /// Folder containing charts produced by the ChartBuilder window. Subfolder of the root folder.
        /// </summary>
        public static string PathToChartFolder { get { return RequireSubfolder(CHART_FOLDER); } }

        static NodeEditorSettings()
        {
            defaultNodeStyle = new GUIStyle();
            defaultNodeStyle.normal.background = EditorGUIUtility.Load(DEFAULT_BACKGROUND_PATH) as Texture2D;
            defaultNodeStyle.border = STYLE_BORDER;

            selectedNodeStyle = new GUIStyle();
            selectedNodeStyle.normal.background = EditorGUIUtility.Load(SELECTED_BACKGROUND_PATH) as Texture2D;
            selectedNodeStyle.border = STYLE_BORDER;
        }

        static string RequireSubfolder(string name)
        {
            string rootPath = PathToRootFolder;
            string folderPath = IOHelpers.RequireFolder(rootPath, name);
            return folderPath;
        }
    } 
}