namespace CaveGeneration.HeightMaps
{
    static class Tooltips
    {
        public const string HEIGHT_MAP_MAX_HEIGHT = "how much the height map can deviate from the base height of the walls";
        public const string HEIGHT_MAP_SCALE = "Level of smoothness of height map - think rolling hills vs jagged mountains.";
        public const string HEIGHT_MAP_NUM_LAYERS =
            "The number of height maps to stack onto eachother, each more compressed and with smaller contribution.";
        public const string HEIGHT_MAP_AMP_DECAY = "How quickly the contribution of subsequent layers is reduced.";
        public const string HEIGHT_MAP_FREQ_GROWTH = "How much more compressed each subsequent layer becomes.";
        public const string HEIGHT_MAP_VISUALIZE =
            "If selected, will visualize a sample of the height map generated by the current parameters in the inspector.";
    }
}