using UnityEngine;
using System.Collections;

namespace CaveGeneration
{
    public abstract class HeightMap : MonoBehaviour, IHeightMap
    {
        public float maxHeight;

        [Tooltip("Level of smoothness of height map - think rolling hills vs jagged mountains.")]
        public float scale;

        [Tooltip("The number of height maps to stack onto eachother, each more compressed and with smaller contribution.")]
        public int numLayers;

        [Tooltip("How quickly the contribution of subsequent layers is reduced.")]
        [Range(0.001f, 1f)]
        public float amplitudeDecay;

        [Tooltip("How much more compressed each subsequent layer becomes.")]
        public float frequencyGrowth;

        [Tooltip("If selected, will visualize a sample of the height map generated by the current parameters in the inspector.")]
        public bool visualize = false;

        protected Noise noise;
        HeightMapDrawer drawer;

        public void Create(int seed)
        {
            float amplitudePersistance = 1 - amplitudeDecay;
            noise = new Noise(numLayers, amplitudePersistance, frequencyGrowth, scale, seed);
        }

        public virtual float GetHeight(float x, float y)
        {
            return maxHeight * noise.GetHeight(x, y);
        }

        void OnValidate()
        {
            if (numLayers < 1)
            {
                numLayers = 1;
            }
            if (maxHeight <= 0)
            {
                maxHeight = 0.001f;
            }
            if (scale <= 0)
            {
                scale = 0.0001f;
            }
            if (frequencyGrowth < 1)
            {
                frequencyGrowth = 1;
            }
            if (visualize)
            {
                UpdateDrawer();
            }
        }

        void UpdateDrawer()
        {
            Create(seed: 0);
            if (drawer == null)
            {
                drawer = new HeightMapDrawer(GetHeight);
            }
            drawer.BuildMesh(GetHeight);
        }

        void OnDrawGizmos()
        {
            if (visualize)
            {
                Gizmos.DrawMesh(drawer.mesh);
            }
        }
    } 
}
