using UnityEngine;
using System.Collections;

namespace CaveGeneration
{
    /// <summary>
    /// A generalization of perlin noise, this class allows the generation of continuously varying, random values
    /// designed with terrain in mind.
    /// </summary>
    public abstract class HeightMap : MonoBehaviour, IHeightMap
    {
        public float maxHeight;

        [Tooltip("Level of smoothness of height map - think rolling hills vs jagged mountains.")]
        public float scale;

        [Tooltip("The number of height maps to stack onto eachother, each more compressed and with smaller contribution.")]
        public int numLayers;

        [Tooltip("How quickly the contribution of subsequent layers is reduced.")]
        [Range(0.001f, 1f)]
        public float amplitudeDecay;

        [Tooltip("How much more compressed each subsequent layer becomes.")]
        public float frequencyGrowth;

        [Tooltip("If selected, will visualize a sample of the height map generated by the current parameters in the inspector.")]
        public bool visualize = false;

        protected Noise noise;
        HeightMapDrawer drawer;

        /// <summary>
        /// Once parameter selection is finalized, use this method to initialize the height map with a specific seed.
        /// </summary>
        public void Initialize(int seed)
        {
            float amplitudePersistance = 1 - amplitudeDecay;
            noise = new Noise(numLayers, amplitudePersistance, frequencyGrowth, scale, seed);
        }

        /// <summary>
        /// Get a randomized height value between 0 and max height based on the parameters supplied when Initialize was 
        /// called. Repeated calls to GetHeight with the same parameters will return the same value. Method is analogous 
        /// to Mathf.PerlinNoise. 
        /// </summary>
        public virtual float GetHeight(float x, float y)
        {
            if (noise == null)
            {
                Initialize(Time.renderedFrameCount);
            }
            return maxHeight * noise.GetHeight(x, y);
        }

        void OnValidate()
        {
            if (numLayers < 1)
            {
                numLayers = 1;
            }
            if (maxHeight <= 0)
            {
                maxHeight = 0.001f;
            }
            if (scale <= 0)
            {
                scale = 0.0001f;
            }
            if (frequencyGrowth < 1)
            {
                frequencyGrowth = 1;
            }
            if (visualize)
            {
                UpdateDrawer();
            }
        }

        void UpdateDrawer()
        {
            Initialize(seed: 0);
            if (drawer == null)
            {
                drawer = new HeightMapDrawer(GetHeight);
            }
            drawer.BuildMesh(GetHeight);
        }

        void OnDrawGizmos()
        {
            if (visualize)
            {
                Gizmos.DrawMesh(drawer.mesh);
            }
        }
    } 
}
